# Sample .travis.yml for R projects
language: r
sudo: false
cache: packages

r_packages:
  - covr

warnings_are_errors: false
notifications:
  on_success: always
  on_failure: always

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libgsl0-dev

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes"
    - R_CHECK_ARGS="--no-build-vignettes --as-cran"

after_success:
  - travis_wait 40 Rscript -e "covr::codecov()"


# language: c
#
# sudo: required
#
# dist: bionic
#
# before_install:
#   - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
#   - ./run.sh bootstrap
#
# install:
#   - ./run.sh install_aptget libgsl-dev r-cran-rcpp r-cran-mass r-cran-rcppgsl r-cran-tweedie r-cran-statmod r-cran-testthat
#
# script:
#   - ./run.sh run_tests
#
# after_failure:
#   - ./run.sh dump_logs
#
# notifications:
#   email:
#     on_success: change
#     on_failure: change
