# Sample .travis.yml for R projects
language: r
sudo: false
cache: packages

r_packages:
  - covr

warnings_are_errors: false
notifications:
  on_success: always
  on_failure: always

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libgsl0-dev

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes"
    - R_CHECK_ARGS="--no-build-vignettes --as-cran"

after_success:
  - travis_wait 40 Rscript -e "covr::codecov()"


