# Sample .travis.yml for R projects
language: r
sudo: false
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

warnings_are_errors: false
notifications:
  on_success: always
  on_failure: always

env:
  global:
    - travis_wait 40 R_BUILD_ARGS="--no-build-vignettes"
    - travis_wait 40 R_CHECK_ARGS="--no-build-vignettes --as-cran"
