#' @export
"effects_data.regional_mix" <- function(focal.predictors, mod, ngrid = 50, ...){

  # focal.predictors <- c("x1.1","x1.2","x1.3","x2.1","x2.2","x2.3")
  # mod <- fm_regional_mix
  # ngrid <- 50

  if (is.null(mod$titbits))
    stop("Model doesn't contain all information required for effectsPlotData.
         Please supply model with titbits (from titbits=TRUE in regional_mix call)")

  Mode <- function(x, na.rm = FALSE) {
    if (na.rm) {
      x = x[!is.na(x)]
    }
    ux <- unique(x)
    return(ux[which.max(tabulate(match(x, ux)))])
  }

  ## set up the data objects
  X <- mod$titbits$X
  W <- mod$titbits$W

  ## set up the variables in the formula
  tt <- terms(mod$titbits$rcp_formula)
  tt <- delete.response(tt)
  vars <- all.vars(parse(text=tt))
  if(!is.null(W) && ncol(W)>1){
    tt2 <- terms(mod$titbits$species_formula)
    tt2 <- delete.response(tt2)
    vars <- c(vars,all.vars(parse(text=tt2)))
  }
  nvars = length(vars)

  pred.data <- mod$titbits$data
  pred.data <- pred.data[,vars,drop=FALSE]

  ## check for factors
  factors <- NULL
  for(ii in 1:nvars){
    factors[ii] <- is.factor(pred.data[,vars[ii]]) | is.character(pred.data[,vars[ii]])
  }

  ## check for binary data (i.e factors that have been expanded before modelling as per model.matrix)
  binary <- apply(pred.data,2,function(x) { all(x %in% 0:1) })

  ## check for focal.predictors in pred.data
  focal.ids <- lapply(focal.predictors, grep, colnames(pred.data))

  # lists for data structures
  mfs <- list() #catch model.frames
  f.focal <- list()
  v.focal <- list()
  n.focal <- list()
  for(i in 1:length(focal.ids)){

    f.focal[[i]] <- factors[focal.ids[[i]]]
    if(any(f.focal[[i]])) v.focal[[i]] <- pred.data[, focal.ids[[i]]]
    else v.focal[[i]] <- pred.data[, focal.ids[[i]],drop=FALSE]
    n.focal[[i]] <- seq_len(nvars)[-unlist(focal.ids[[i]])]

    xx <- list()
    for(j in 1:length(focal.ids[[i]])){
      if(f.focal[[i]][j]) {
        xx[[j]] = levels(v.focal[[i]][j])
        ngrid = length(xx)
      } else {
        mi = min(v.focal[[i]][j])
        ma = max(v.focal[[i]][j])
        xx[[j]] = seq(mi, ma, length.out = ngrid)
      }
    }
    XDataNew = data.frame(xx, stringsAsFactors = TRUE)
    colnames(XDataNew) = vars[focal.ids[[i]]]
    for (k in seq_len(length(n.focal[[i]]))) {
      non.focal = n.focal[[i]][k]
      f.non.focal = factors[non.focal]
      v.non.focal = pred.data[, vars[non.focal]]
      if (f.non.focal) {
        XDataNew[, vars[non.focal]] = Mode(v.non.focal)
      }
      if (!f.non.focal) {
        v.non.focal = pred.data[, vars[non.focal]]
        XDataNew[, vars[non.focal]] = mean(v.non.focal)
      }
    }
    mfs[[i]] <- XDataNew[,vars,drop=FALSE]
  }

  names(mfs) <- focal.predictors
  class(mfs) <- "regional_mix_effects_data"

  return(mfs)

}

#' @rdname plot.regional_mix_effects_data
#' @name plot.regional_mix_effects_data
#' @title plot.regional_mix_effects_data
#' @param x a list of partial prediction data frames as generated by
#' effects_data.
#' @param object A fitted regional_mix model.
#' @param boot.object A regional_mix.bootstrap object. Default is NULL, no standard
#' errors will be reported.
#' @param nboot An option to do bootstrapping when plotting, this will be slow,
#' better to run and save a bootstrap object and pass to the plotting function as
#' boot.object.
#' @param response.var Which RCPs to plot on the y-axis. Default is all RCPs.
#' Can be a subset, using the names stored in \code{object$names$RCPs} (e.g. "RCP_1").
#' @param CI is the confidence intervals for the standard errors.
#' @param linecols Are the default colours for plotting the partial responses.
#' @param polycols Is the colour of the confidence intervals in the response plots.
#' @param ylim Default is NULL and will plot ylim within range of the response variable.
#' @param \\dots Extra plotting arguments.
#' @details Plots the partial dependence plots (marginal response curves) for
#' focal covariates. Continuous covariates will be plotted as lines, factors
#' will be plotted as dotplots. RCP predictions are probabilities, so unlike
#' \link[ecomix]{plot.species_mix_effects_data} there is no link/response scale option.
#' @importFrom abind adrop
#' @importFrom stats .checkMFClasses delete.response formula terms
#' @importFrom graphics axis
#' @importFrom utils stack
#' @export
"plot.regional_mix_effects_data" <- function(x, object, boot.object = NULL,
                                              nboot = 0,
                                              response.var = NULL,
                                              CI = c(0.025, 0.975),
                                              linecols = c("#1B9E77","#D95F02","#7570B3",
                                                           "#E7298A","#66A61E","#E6AB02",
                                                           "#A6761D","#666666"),
                                              polycols = "#00000020", ylim=NULL, ...){

  nam <- paste("RCP", seq_len(object$nRCP), sep = "_")
  if(is.null(response.var)) response.var <- nam
  if(! all(response.var %in% nam))
    stop("Unknown RCP. Options are any of: ", paste(nam,collapse=", "))

  ## function to add a random row to deal with poly degree error.
  add_row <- function(x, degree = 2){

    factors <- NULL
    for( i in 1:ncol(x)){
      factors[i] <- is.factor(x[,i])
    }

    x[nrow(x) + 1:degree ,factors] <- unique(x[nrow(x),factors])
    x[nrow(x) + ((1:degree)-degree) ,!factors] <- rnorm(ncol(x[nrow(x),!factors,drop=FALSE])*degree,sd=1e-6)

    return(x)

  }

  xnew <- lapply(x,add_row)

  partial.preds <- suppressMessages(lapply(xnew, function(ii) predict(object=object, object2=boot.object,
                                                                      newdata = ii,
                                                                      nboot = nboot, alpha=CI[2]-CI[1])))

  ## remove the dummy columns
  remove_dummy_rows <- function(x, partial.preds){

    nrow.orig <- nrow(x)

    if(length(partial.preds)==4){
      partial.preds$ptPreds <- partial.preds$ptPreds[1:nrow.orig, ,drop=FALSE]
      partial.preds$bootPreds <- partial.preds$bootPreds[1:nrow.orig, ,drop=FALSE]
      partial.preds$bootSEs <- partial.preds$bootSEs[1:nrow.orig, ,drop=FALSE]
      partial.preds$bootCIs <- partial.preds$bootCIs[1:nrow.orig, , , drop=FALSE]
    } else {
      partial.preds <- partial.preds[1:nrow.orig, ,drop=FALSE]
    }

    return(partial.preds)

  }

  partial.preds <- lapply(1:length(x),function(ii)remove_dummy_rows(x[[ii]],partial.preds[[ii]]))
  names(partial.preds) <- names(x)

  ylabel <- "Probability"

  for (i in seq_len(length(partial.preds))){

    se.plots <- FALSE
    if(length(partial.preds[[i]])==4) se.plots <- TRUE

    idx <- which(nam %in% response.var)

    xlabel <- names(x[i])
    xx <- x[[i]][,names(x[i])]
    fac.var <- is.factor(xx)

    cols <- linecols
    cols <- rep(cols,100)

    if(se.plots){

      yy.mn <- partial.preds[[i]]$bootPreds[,idx,drop=FALSE]
      yy.lwr <- abind::adrop(partial.preds[[i]]$bootCIs[,idx,1,drop=FALSE],drop=3)
      yy.upp <- abind::adrop(partial.preds[[i]]$bootCIs[,idx,2,drop=FALSE],drop=3)

      lo1 <- min(yy.lwr)
      hi1 <- max(yy.upp)

      if(is.null(ylim)) ylimy <- c(lo1,hi1)
      else ylimy <- ylim

      if(!fac.var){
        matplot(xx, yy.mn, ylim = ylimy,
                type = "l",
                xaxt = "n", xlab = xlabel, ylab = ylabel)
        axis(1, c(min(xx), (min(xx) + max(xx))/2, max(xx)),round(c(min(xx), (min(xx) + max(xx))/2, max(xx)),2))
        for(j in seq_len(ncol(yy.lwr))){
          polygon(c(xx, rev(xx)), c(yy.lwr[,j], rev(yy.upp[,j])),
                  col = polycols, border = FALSE)
          lines(xx, yy.mn[,j], col=cols[j], lwd = 2)
        }
        legend(x="topleft",
               legend=dimnames(yy.mn)[[2]],
               col=cols[1:length(dimnames(yy.mn)[[2]])],
               lty=1,
               cex=0.9,
               bty="n")

      } else {
        params <- cbind(xx,
                        utils::stack(as.data.frame(yy.mn))[,2:1],
                        utils::stack(as.data.frame(yy.lwr))[,1],
                        utils::stack(as.data.frame(yy.upp))[,1])
        colnames(params) <- c("ftr","grp","mean","lower","upper")

        if(is.null(ylim)) ylimy <- range(c(params$lower,params$upper))+c(-0.02,0.02)
        else ylimy <- ylim

        axis.locs <- seq(.5,by=.5,length.out=length(unique(params$ftr)))
        locs <- rep(axis.locs,each= length(unique(params$grp)))+seq(-0.05,0.05,length.out = length(unique(params$grp)))
        plot(mean~locs,
             data = params,
             type = "n",
             xlab = xlabel,
             ylab = ylabel,
             axes = FALSE,
             bty = "n",
             xlim = c(0.25, (max(axis.locs)+.25)),
             ylim = ylimy)
        axis(side = 2, tcl = -0.3)
        axis(side = 1, lty = 0, at = axis.locs, labels = unique(params$ftr), las = 1, col.lab = grey(0.3))

        for (k in seq_len(nrow(params))) {
          lines(y = c(params$lower[k], params$upper[k]),
                x = cbind(locs[k], locs[k]),
                lwd = 4,
                col = linecols[as.numeric(rep(unique(params$grp),length(unique(params$ftr)))[k])])
        }

        points(params$mean~locs,
               pch = 16,
               cex  = 1.5,
               col = linecols[as.numeric(rep(unique(params$grp),length(unique(params$ftr))))])

        legend(x="topleft",
               legend=unique(params$grp),
               col= linecols[as.numeric(unique(params$grp))],
               pch=16,
               cex=0.9,
               bty="n")

      }

    } else {

      yy.mn <- partial.preds[[i]][,idx,drop=FALSE]

      lo1 <- min(yy.mn)
      hi1 <- max(yy.mn)

      if(is.null(ylim)) ylimy <- c(lo1,hi1)
      else ylimy <- ylim

      if(!fac.var){
        matplot(xx, yy.mn, ylim = ylimy,
                type = "l", xaxt = "n", xlab = xlabel, ylab = ylabel)
        axis(1, c(min(xx), (min(xx) + max(xx))/2, max(xx)),round(c(min(xx), (min(xx) + max(xx))/2, max(xx)),2))
        for(j in seq_len(ncol(yy.mn))){
          lines(xx, yy.mn[,j], col=cols[j], lwd = 2)
        }
        legend(x="topleft",
               legend=dimnames(yy.mn)[[2]],
               col=cols[1:length(dimnames(yy.mn)[[2]])],
               lty=1,
               cex=0.9,
               bty="n")

      } else {
        params <- cbind(xx, utils::stack(as.data.frame(yy.mn))[,2:1])
        colnames(params) <- c("ftr","grp","mean")

        if(is.null(ylim)) ylimy <- range(c(params$mean))+c(-0.02,0.02)
        else ylimy <- ylim

        axis.locs <- seq(.5,by=.5,length.out=length(unique(params$ftr)))
        locs <- rep(axis.locs,each= length(unique(params$grp)))+seq(-0.05,0.05,length.out = length(unique(params$grp)))
        plot(mean~locs,
             data = params,
             type = "n",
             xlab = xlabel,
             ylab = ylabel,
             axes = FALSE,
             bty = "n",
             xlim = c(0.25, (max(axis.locs)+.25)),
             ylim = ylimy)
        axis(side = 2, tcl = -0.3)
        axis(side = 1, lty = 0, at = axis.locs, labels = unique(params$ftr), las = 1, col.lab = grey(0.3))

        points(params$mean~locs,
               pch = 16,
               cex  =1.5,
               col = linecols[as.numeric(rep(unique(params$grp),length(unique(params$ftr))))])

        legend(x="topleft",
               legend=unique(params$grp),
               col= linecols[as.numeric(unique(params$grp))],
               pch=16,
               cex=0.9,
               bty="n")

      }
    }
  }

}
